apiVersion: apps/v1
kind: Deployment
metadata:
  name: lightspeed-chroma-db
spec:
  selector:
    matchLabels:
      project: lightspeed
  replicas: 1
  template:
    metadata:
      labels:
        project: lightspeed
    spec:
      containers:
      - name: chromadb
        image: quay.io/ilan_pinto/chromadb
      ports:
        - containerPort:  8000
          name:  http
--- 

apiVersion: v1
kind: Service
metadata:
  name: chromadb-service
  labels:
    project: lightspeed
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    project: lightspeed
